// <auto-generated/>
namespace TypeSunny
{
internal static class CompiledReleaseIdentity
{
public const string Version = "20260627";
public static readonly long PackagePublishedUtcTicks = 0L;
public static System.DateTime PackagePublishedUtc => ReleaseIdentity.FromUtcTicks(PackagePublishedUtcTicks);
}
}
