// <auto-generated/>
namespace TypeSunny
{
internal static class CompiledReleaseIdentity
{
public const string Version = "20260604";
public static readonly long PackagePublishedUtcTicks = 639161336782485373L;
public static System.DateTime PackagePublishedUtc => ReleaseIdentity.FromUtcTicks(PackagePublishedUtcTicks);
}
}
